sudo: false
language: java
jdk: oraclejdk7
before_install:
   - pip install --user codecov
   - gpg --allow-secret-key-import --import .gpg
   - gpg --list-secret-keys
install: mvn clean deploy --settings .travis-settings.xml
after_success: 
   - codecov
branches:
  only:
   - master
   - coverity_scan
env:
  global:
   # OSS_USERNAME
   - secure: "F+D8Ab3VljNY4w0SGOHLymUcxmisIJDMnSbLDfcW1VGRMOgNiGn79/7Vf4O9HeCd0XnQRJ9n1d5538ITqBnSCpZuMHwqLyHxJHC95wmpA8V1UYVA95TUHCH9Dd1372JK3uI05ZnVXUFLT1FHAYNbgVVMuJf/yyzaTZgeuRb4epY="
   # OSS_PASSWORD
   - secure: "erME4L4b57ZGgvppUTEl6mIK9UugihJN3PpISfxzXiS3JlYFCGFa1dDF+hHU0MUcobjvzO6QpwizKQ8rH7F9oqgSlGg3vi0wLSVA3arPHyrGvcp21ViubxHkPg9lfX/SfRCspa/nNGGnHRaJmabbnDnMlxRqyQuFUOf93v+mduc="
   # GPG_PASSPHRASE
   - secure: "N+gUkhYkGQtkI/gajXdlz0Wl/xuNcwM8o5p/xXnnu0+diDrl/TNDBg9tO6xv6kNsFH4Rn9UpP5g6AbB79JPlZJ2/wzdyWuQRZfCcr2NOxedGp7peOsEqpGhZmk1z8Jn4OF9WiDPvc5qxoQ1ilUM3mH5wXCSXHULTHvZFdNafYZE="
   # COVERITY_SCAN_TOKEN
   - secure: "A4k3D6+FsZ1I5vUF9pAtXsZZxltthBb00jLXwP+pwe+Zfmf7rxAUL+01gUf5+ZoacWOKvgj+OdWJGCJMun3XaPGXpPWL0fIyWv8SvPQAIzHj9SnpoSHH+zpUHsEoq/m1MpzExWiBa4XEFIKCzTbPqWyOBbV/LGOYK6AQtRamJuc="
   # FOO
   - secure: "S0PI3v8dXWrQtXtUKtc7lLvW6S9aTNPs1BKR0rYm9xKHvOX2xyPhoBMIP8hclrDsDMPDjZPQ7vqRN6IpiwkUazbbOerTMTykKVUuzdd2DwCMl7/atHYq75OA0wU1m6quXFxGnCREM2Yo2dsA/9KpmvejT4G+j8bquo28srRna6E="

addons:
   coverity_scan:
      project:
         name: "ocelotds/ocelot"
         description: "Build submitted via Travis CI"
      notification_email: "francois.achache@gmail.com"
      build_command_prepend: "mvn clean"
      build_command: "mvn compile -DskipTests=true -Dgpg.skip=true"
      branch_pattern: coverity_scan

