sudo: false
language: java
jdk: oraclejdk7
before_install:
   - openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in oss.gpg.enc -out oss.gpg -d
   - pip install --user codecov
   - mvn clean install -DskipTests=true
install: mvn deploy --settings .travis-settings.xml
after_success: 
   - codecov
branches:
  only:
   - master
   - coverity_scan
env:
  global:
   # OSS_USERNAME
   - secure: "F+D8Ab3VljNY4w0SGOHLymUcxmisIJDMnSbLDfcW1VGRMOgNiGn79/7Vf4O9HeCd0XnQRJ9n1d5538ITqBnSCpZuMHwqLyHxJHC95wmpA8V1UYVA95TUHCH9Dd1372JK3uI05ZnVXUFLT1FHAYNbgVVMuJf/yyzaTZgeuRb4epY="
   # OSS_PASSWORD
   - secure: "erME4L4b57ZGgvppUTEl6mIK9UugihJN3PpISfxzXiS3JlYFCGFa1dDF+hHU0MUcobjvzO6QpwizKQ8rH7F9oqgSlGg3vi0wLSVA3arPHyrGvcp21ViubxHkPg9lfX/SfRCspa/nNGGnHRaJmabbnDnMlxRqyQuFUOf93v+mduc="
   # GPG_PASSPHRASE
   - secure: "Su5UCKSvwB6Ubw/ouRH9Eh3S3qWGBFbhAU/peuMjN13aQZoSCqL0MCA2dGWLTzgLQmkJGNt8+iIZeLODusFQ0kTaLupBRCJKCMbKVy/cFeJVZ5rdFzJfB5+hBa8sFL8cibARFVIKy9GftSSQKD/TWOOIbOwz3R5B8Wjqp4ylwYA="
   # COVERITY_SCAN_TOKEN
   - secure: "A4k3D6+FsZ1I5vUF9pAtXsZZxltthBb00jLXwP+pwe+Zfmf7rxAUL+01gUf5+ZoacWOKvgj+OdWJGCJMun3XaPGXpPWL0fIyWv8SvPQAIzHj9SnpoSHH+zpUHsEoq/m1MpzExWiBa4XEFIKCzTbPqWyOBbV/LGOYK6AQtRamJuc="

addons:
   coverity_scan:
      project:
         name: "ocelotds/ocelot"
         description: "Build submitted via Travis CI"
      notification_email: "francois.achache@gmail.com"
      build_command_prepend: "mvn clean"
      build_command: "mvn compile -DskipTests=true -Dgpg.skip=true"
      branch_pattern: coverity_scan

